---

- name: "auto_upgrades: Configure /etc/apt/apt.conf.d/20auto-upgrades"
  template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"
    backup: "{{ lp_backup_conf }}"

- name: "auto_upgrades: Disable and stop unattended-upgrades"
  systemd:
    name: "{{ lp_auto_upgrades_service }}"
    state: stopped
    enabled: false
  when: not lp_auto_upgrades_enable|bool

- name: "auto_upgrades: Enable and start unattended-upgrades"
  systemd:
    name: "{{ lp_auto_upgrades_service }}"
    state: started
    enabled: true
  when: lp_auto_upgrades_enable|bool

# EOF
...
