---
# linux-postinstall autofs

- name: "autofs: Debug"
  debug:
    msg: "lp_autofs_enable [ {{ lp_autofs_enable }} ]"
  when: lp_debug|bool

- name: "autofs: Configure {{ lp_autofs_conf_file }}"
  lineinfile:
    dest: "{{ lp_autofs_conf_file }}"
    regexp: "^{{ item.key }}\\s*=\\s*(.*)$"
    line: "{{ item.key }} = {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_autofs_conf }}"
  notify: reload autofs

- name: "autofs: Configure {{ lp_autofs_master_conf_file }}"
  lineinfile:
    dest: "{{ lp_autofs_master_conf_file }}"
    regexp: "^{{ item.key }}\\s*(.*)$"
    line: "{{ item.key }} {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_autofs_master_conf }}"
  notify: reload autofs

- name: "autofs: Configure {{ lp_autofs_misc_conf_file }}"
  lineinfile:
    dest: "{{ lp_autofs_misc_conf_file }}"
    regexp: "^{{ item.key }}\\s*(.*)$"
    line: "{{ item.key }} {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_autofs_misc_conf }}"
  notify: reload autofs

- name: "autofs: Enable and start autofs"
  systemd:
    name: "{{ lp_autofs_service }}"
    enabled: true
    state: started
  when: lp_autofs_enable|bool

- name: "autofs: Stop and disable autofs"
  systemd:
    name: "{{ lp_autofs_service }}"
    enabled: false
    state: stopped
  when: not lp_autofs_enable|bool

# EOF
...
