---
# linux-postinstall bluetooth

- name: "bluetooth: Debug"
  debug:
    msg: "lp_bluetooth_enable [{{ lp_bluetooth_enable }}]"
  when: lp_debug|bool

- name: "bluetooth: Configure /etc/bluetooth/main.conf"
  lineinfile:
    dest: /etc/bluetooth/main.conf
    regexp: "^{{ item.key }}\\s*=(.*)$"
    insertbefore: "^{{ '#' }}{{ item.key }}\\s*=(.*)$"
    line: "{{ item.key }} = {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_bluetooth_main_conf }}"
  notify: restart bluetooth

- name: "bluetooth: Enable and start bluetooth"
  systemd:
    name: "{{ lp_bluetooth_service }}"
    enabled: true
    state: started
  when: lp_bluetooth_enable|bool

- name: "bluetooth: Stop and disable bluetooth"
  systemd:
    name: "{{ lp_bluetooth_service }}"
    enabled: false
    state: stopped
  when: not lp_bluetooth_enable|bool

# EOF
...
