---
# linux-postinstall gpg

- name: "gpg: Install gpg packages"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_gpg_packages }}"

- name: "gpg: Configure ~/.gnupg/gpg.conf"
  template:
    src: gpg.conf.j2
    dest: "/home/{{ item.owner }}/.gnupg/gpg.conf"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "0600"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_gpg_conf_user }}"

# TODO: import keys

# EOF
...
