---

- name: "hosts: Debug"
  vars:
    msg: |
      lp_hosts_default_override
      {{ lp_hosts_default_override|default('UNDEFINED')|to_yaml }}
      lp_hosts_default
      {{ lp_hosts_default|to_yaml }}
      lp_hosts
      {{ lp_hosts|to_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug|bool

- name: "hosts: Configure hosts in /etc/hosts"
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: "0644"
    backup: "{{ lp_backup_conf }}"

# EOF
...
