---
# linux-postinstall kvm

- name: "kvm: Debug"
  vars:
    msg: |
      lp_kvm_packages
      {{ lp_kvm_packages|to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
  when: lp_kvm_debug|bool
  tags: lp_kvm_debug

- name: "kvm: Install packages"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_kvm_packages }}"
  tags: lp_kvm_packages

# EOF
...
