---
# linux-postinstall LaTeX

- name: "latex: Install packages"
  include_tasks: fn/install-package.yml
  loop: "{{ lp_latex_packages }}"
  tags: lp_latex_packages

- name: "latex: Create directory /usr/share/texmf/tex/latex"
  file:
    state: directory
    path: /usr/share/texmf/tex/latex
  tags: lp_latex_dir

- name: "latex: Create directories for macros"
  file:
    state: directory
    path: "{{ item.dest }}"
  loop: "{{ lp_latex_macros }}"
  tags: lp_latex_macros

- name: "latex: Download macros"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    timeout: "{{ lp_latex_download_timeout }}"
  loop: "{{ lp_latex_macros }}"
  ignore_errors: "{{ lp_latex_get_url_ignore_errors }}"
  changed_when: false
  tags: lp_latex_labels

# get_url: check mode reports changes with force enabled
# https://github.com/ansible/ansible/issues/25418

# TODO:
# 1) Compile and register labels.sty
# cd /usr/share/texmf/tex/latex/labels/
# latex labels.ins
# texhash /usr/share/texmf

# EOF
...
