---
# linux-postinstall postfix

- name: "postfix: Configure /etc/postfix/main.cf"
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: "^\\s*{{ item.key }}\\s*=\\s*(.*)$"
    line: "{{ item.key }} = {{ item.value }}"
    create: true
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_postfix_main_conf }}"
  notify: reload postfix
  tags: lp_postfix_conf

- name: "postfix: Enable and start postfix"
  systemd:
    name: "{{ lp_postfix_service }}"
    enabled: true
    state: started
  when: lp_postfix_enable|bool
  tags: lp_postfix_service

- name: "postfix: Disable and stop postfix"
  systemd:
    name: "{{ lp_postfix_service }}"
    enabled: false
    state: stopped
  when: not lp_postfix_enable|bool
  tags: lp_postfix_service

# EOF
...
