---
# linux-postinstall ssh

- name: "ssh: Debug"
  vars:
    msg: |
      lp_ssh_config
      {{ lp_ssh_config|to_yaml }}
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
  when: lp_ssh_debug|bool
  tags: lp_ssh_debug

- name: "ssh: Configure /etc/ssh/ssh_config"
  template:
    src: ssh_config.j2
    dest: /etc/ssh/ssh_config
    backup: "{{ lp_backup_conf }}"
  tags: lp_ssh_conf

# EOF
...
