---
# linux-postinstall sshd

- name: "sshd: Configure /etc/ssh/sshd_config"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^\\s*{{ item.key }}\\s*(.*)$"
    insertbefore: "^{{ '#' }}{{ item.key }}\\s*(.*)$"
    line: "{{ item.key }} {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
    validate: "{{ lp_sshd_path }} -t -f %s"
  loop: "{{ lp_sshd_config }}"
  notify: reload sshd
  tags: lp_sshd_config

- name: "sshd: Enable and start sshd"
  systemd:
    name: "{{ lp_sshd_service }}"
    enabled: true
    state: started
  when: lp_sshd_enable|bool
  tags: lp_sshd_service

- name: "sshd: Disable and stop sshd"
  systemd:
    name: "{{ lp_sshd_service }}"
    enabled: false
    state: stopped
  when: not lp_sshd_enable|bool
  tags: lp_sshd_service

# EOF
...
