---
# linux-postinstall sudoers

- name: "sudoers: Configure /etc/sudoers"
  lineinfile:
    path: /etc/sudoers
    line: "{{ item.line }}"
    state: "{{ item.state|default('present') }}"
    create: true
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_sudoers_conf }}"

- name: "sudoers: Configure /etc/sudoers.d/01"
  lineinfile:
    path: /etc/sudoers.d/01
    line: "{{ item }}"
    owner: "{{ lp_sudoers_owner }}"
    group: "{{ lp_sudoers_group }}"
    mode: "{{ lp_sudoers_mode }}"
    create: true
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_sudoers_01 }}"

# EOF
...
