---
# linux-postinstall swap

- name: "swap: Debug"
  vars:
    msg: |
      lp_swap [{{ lp_swap }}]
      lp_swap_enable [{{ lp_swap_enable }}]
      lp_swap_file [{{ lp_swap_file|default("UNDEFINED") }}]
      lp_swap_size [{{ lp_swap_size|default("UNDEFINED") }}]
      lp_swap_stsize [{{ lp_swap_stsize|default("UNDEFINED") }}]
  debug:
    msg: "{{ msg.split('\n')[:-1] }}"
  when: lp_swap_debug|bool
  tags: lp_swap_debug

- name: "swap: Create swapfile {{ lp_swap_file }}"
  shell: sh -c 'if [ ! -e {{ lp_swap_file }} ]; then printf "create"; fi'
  register: command_result
  changed_when: command_result.stdout == "create"
  notify: create and mount swap file
  tags: lp_swap_swapfile

- name: "swap: Change swapfile {{ lp_swap_file }}"
  shell: >
    sh -c
    'if [ -e {{ lp_swap_file }} ] &&
    [ "`stat --format '%s' {{ lp_swap_file }}`" -ne "{{ lp_swap_stsize }}" ];
    then printf "change";
    fi'
  register: command_result
  changed_when: command_result.stdout == "change"
  notify: change and mount swap file
  tags: lp_swap_swapfile

- name: "swap: Create swap entry in /etc/fstab"
  mount:
    name: "none"
    src: "{{ lp_swap_file }}"
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
    state: present
    backup: "{{ lp_backup_conf }}"
  when: lp_swap_enable|bool
  tags: lp_swap_fstab

- name: "swap: Remove swap entry from /etc/fstab"
  mount:
    name: "none"
    src: "{{ lp_swap_file }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: absent
    backup: "{{ lp_backup_conf }}"
  notify: remove swap file
  when:
    - not lp_swap_enable|bool
    - lp_swap_file is defined
  tags: lp_swap_swapfile

# EOF
...
