---
# linux-postinstall sysctl

- name: "sysctl: Configure /etc/sysctl.conf"
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^\\s*{{ item.var }}\\s*=(.*)$"
    line: "{{ item.var }} = {{ item.value }}"
    backup: "{{ lp_backup_conf }}"
  loop: "{{ lp_sysctl_vars }}"
  notify: load sysctl settings

# EOF
...
