---

- name: "timesyncd: Debug"
  vars:
    msg: |
      lp_timesyncd [{{ lp_timesyncd }}]
      lp_timesyncd_NTP [{{ lp_timesyncd_NTP }}]
      lp_timesyncd_FallbackNTP [{{ lp_timesyncd_FallbackNTP }}]
      lp_timesyncd_RootDistanceMaxSec [{{ lp_timesyncd_RootDistanceMaxSec }}]
      lp_timesyncd_PollIntervalMinSec [{{ lp_timesyncd_PollIntervalMinSec }}]
      lp_timesyncd_PollIntervalMaxSec [{{ lp_timesyncd_PollIntervalMaxSec }}]
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug|bool
  tags: lp_timesyncd_debug

- name: "timesyncd: Configure /etc/systemd/timesyncd.conf"
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: "0644"
    backup: "{{ lp_backup_conf }}"
  notify: restart timesyncd
  tags: lp_timesyncd_conf

- name: "timesyncd: Enable and start timesyncd"
  service:
    name: "{{ lp_timesyncd_service }}"
    state: started
    enabled: true
  when: lp_timesyncd_enable|bool
  tags: lp_timesyncd_service

- name: "timesyncd: Disable and stop timesyncd"
  service:
    name: "{{ lp_timesyncd_service }}"
    state: stopped
    enabled: false
  when: not lp_timesyncd_enable|bool
  tags: lp_timesyncd_service

# Notes on CentOS
# * systemd compiled without timesyncd service in CentOS 7 ?
# * use ntpd or chrony only ?
# https://unix.stackexchange.com/questions/286708/
# centos-7-2-minimal-time-synchronization-timedated-and-or-ntpd-chrony
# https://www.freedesktop.org/wiki/Software/systemd/timedated/

# EOF
...
