---

- name: "timezone: Debug"
  debug:
    msg: "lp_timezone_zoneinfo [{{ lp_timezone_zoneinfo }}]"
  when: lp_debug|bool

- name: "timezone: Set timezone {{ lp_timezone_zoneinfo }}"
  timezone:
    name: "{{ lp_timezone_zoneinfo|default('UTC') }}"

# EOF
...
