---

- name: "users: Debug"
  vars:
    msg: |
      lp_users
      {{ lp_users|to_nice_yaml }}
      lp_users_groups
      {{ lp_users_groups|to_nice_yaml }}
  debug:
    msg: "{{ msg.split('\n') }}"
  when: lp_debug|bool

- name: "users: Add or update users"
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell|default(omit) }}"
    password: "{{ item.password|default(omit) }}"
    update_password: "{{ item.update_password|default(omit) }}"
  loop: "{{ lp_users }}"

- name: "users: Add users to additional groups"
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: true
  loop: "{{ lp_users_groups }}"

#  EOF
...
