---
# linux-postinstall zeitgeist

# One-way atm
- name: "zeitgeist: Remove zeitgeist"
  apt:
    state: absent
    name: zeitgeist
    purge: true
  when: not lp_zeitgeist_install|bool

- name: "zeitgeist: Remove zeitgeist-*"
  apt:
    state: absent
    name: zeitgeist-*
    purge: true
  when: not lp_zeitgeist_install|bool

# - name: Disable zeitgeist
#   service:
#     name: zeitgeist
#     state: stopped
#     enabled: no
#   when: not lp_zeitgeist
# "Could not find the requested service zeitgeist"

# for i in zeitgeist-fts zeitgeist; do
# systemctl --user disable $i;
# systemctl --user stop $i;
# systemctl --user mask $i;
# done

# EOF
...
