---
# linux-postinstall zeitgeist

# One-way atm
- name: Remove zeitgeist
  apt:
    state: absent
    name: zeitgeist
    purge: true
  when:
    - not lp_zeitgeist|bool
    - ansible_os_family == "Debian"

- name: Remove zeitgeist-*
  apt:
    state: absent
    name: zeitgeist-*
    purge: true
  when:
    - not lp_zeitgeist|bool
    - ansible_os_family == "Debian"

# - name: Disable zeitgeist
#   service:
#     name: zeitgeist
#     state: stopped
#     enabled: no
#   when: not lp_zeitgeist
# "Could not find the requested service zeitgeist"

# for i in zeitgeist-fts zeitgeist; do
# systemctl --user disable $i;
# systemctl --user stop $i;
# systemctl --user mask $i;
# done

# EOF
...
