---

- hosts: localhost
  gather_facts: false

  tasks:

    - name: Include variables
      include_vars:
        file: annotation/annotation-tasks.yml
    - name: Create rst file
      template:
        src: annotation/annotation-tasks.rst.j2
        dest: source/annotation-tasks.rst

# EOF
...
